# AUTO-GENERATED by tools/benchmark/TestSindbadTEM/derive_sindbadTEM_test_data.jl -- do not hand-edit.
# Regenerate with: julia --project=. tools/benchmark/TestSindbadTEM/derive_sindbadTEM_test_data.jl

using SindbadTEM
using StaticArrays: SVector
using Dates

tmp_forcing = (;
    f_ambient_CO2 = 400.73672f0,
    f_clay = Float32[0.23; 0.2; 0.22; 0.25; 0.27; 0.28; 0.28;;],
    f_dist_intensity = 0.0f0,
    f_burnt_area = 0.0f0,
    f_crop_harvest_efficiency = 0.0f0,
    f_crop_harvest_intensity = 0.0f0,
    f_is_crop_harvested = 0.0f0,
    f_is_wood_harvested = 0.0f0,
    f_tree_frac = 0.0f0,
    f_frac_vegetation = 1.0f0,
    f_pft = 5.0f0,
    f_orgm = Float32[0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0;;],
    f_PAR = 9.345097f0,
    f_rain = 1.1867276f0,
    f_rg = 18.690193f0,
    f_rg_pot = 30.86505f0,
    f_rn = 7.8920016f0,
    f_sand = Float32[0.58; 0.6; 0.58; 0.56; 0.54; 0.53; 0.54;;],
    f_silt = Float32[0.2; 0.2; 0.2; 0.2; 0.19; 0.19; 0.18;;],
    f_airT = 19.122822f0,
    f_airT_day = 21.237083f0,
    f_VPD = 0.8669716f0,
    f_VPD_day = 1.1897867f0,
    f_wood_harvest_efficiency = 0.0f0,
    f_wood_harvest_intensity = 0.0f0,
    f_EVI = 0.98906744f0,
    f_LAI = 1.0023049f0,
    f_NDVI = 0.98906744f0,
    f_NDWI = 0.98906744f0,
    f_NIRv = 0.98906744f0,
    f_PET = 7.473666f0,
    f_fAPAR = 0.98906744f0,
    f_rain_int = 5.9336386f0,
    f_snow = 0.11867279f0,
    f_psurf_day = 110.0f0,
    f_AWC = 25.0f0,
    f_RDmax = 50.0f0,
    f_RDeff = 40.0f0,
    f_SWCmax = 55.0f0,
    f_frac_frozen_soil = 0.0f0
)
