# AUTO-GENERATED by tools/benchmark/TestSindbadTEM/derive_sindbadTEM_test_data.jl -- do not hand-edit.
# Regenerate with: julia --project=. tools/benchmark/TestSindbadTEM/derive_sindbadTEM_test_data.jl

using SindbadTEM
using StaticArrays: SVector
using Dates

tmp_helpers = (;
    dates = NamedTuple(),
    run = (;
    catch_model_errors = DoNotCatchModelErrors()
),
    numbers = (;
    tolerance = 0.01f0
),
    pools = (;
    layer_thickness = (;
    cVegRoot = (1.0f0,),
    cVegWood = (1.0f0,),
    cVegLeaf = (1.0f0,),
    cVegReserve = (1.0f0,),
    cLitFast = (1.0f0,),
    cLitSlow = (1.0f0,),
    cSoilSlow = (1.0f0,),
    cSoilOld = (1.0f0,),
    soilW = (50.0f0, 200.0f0, 750.0f0, 1000.0f0),
    groundW = (1.0f0,),
    snowW = (1.0f0,),
    surfaceW = (1.0f0,)
),
    zix = (;
    cVeg = (1, 2, 3, 4),
    cLit = (5, 6),
    cSoil = (7, 8),
    cVegRoot = (1,),
    cVegWood = (2,),
    cVegLeaf = (3,),
    cVegReserve = (4,),
    cLitFast = (5,),
    cLitSlow = (6,),
    cSoilSlow = (7,),
    cSoilOld = (8,),
    cEco = (1, 2, 3, 4, 5, 6, 7, 8),
    soilW = (1, 2, 3, 4),
    groundW = (5,),
    snowW = (6,),
    surfaceW = (7,),
    TWS = (1, 2, 3, 4, 5, 6, 7),
    cLitLeaf = (),
    cLitRoot = (),
    cMic = (),
    cVegRootF = (),
    cVegRootC = (),
    cLitLeafM = (),
    cLitLeafS = (),
    cLitWood = (),
    cLitRootFM = (),
    cLitRootFS = (),
    cLitRootC = (),
    cMicSurf = (),
    cMicSoil = (),
    cProducts = (),
    cProductsWood = (),
    cProductsCrop = ()
),
    components = (;
    cVeg = (:cVegRoot, :cVegWood, :cVegLeaf, :cVegReserve),
    cLit = (:cLitFast, :cLitSlow),
    cSoil = (:cSoilSlow, :cSoilOld),
    cVegRoot = (:cVegRoot,),
    cVegWood = (:cVegWood,),
    cVegLeaf = (:cVegLeaf,),
    cVegReserve = (:cVegReserve,),
    cLitFast = (:cLitFast,),
    cLitSlow = (:cLitSlow,),
    cSoilSlow = (:cSoilSlow,),
    cSoilOld = (:cSoilOld,),
    cEco = (:cVegRoot, :cVegWood, :cVegLeaf, :cVegReserve, :cLitFast, :cLitSlow, :cSoilSlow, :cSoilOld),
    soilW = (:soilW, :soilW, :soilW, :soilW),
    groundW = (:groundW,),
    snowW = (:snowW,),
    surfaceW = (:surfaceW,),
    TWS = (:soilW, :groundW, :snowW, :surfaceW)
),
    all_components = (;
    cEco = (:cVeg, :cLit, :cSoil, :cVegRoot, :cVegWood, :cVegLeaf, :cVegReserve, :cLitFast, :cLitSlow, :cSoilSlow, :cSoilOld),
    TWS = (:soilW, :groundW, :snowW, :surfaceW)
),
    zeros = (;
    cVeg = SVector{4,Float32}((0.0f0, 0.0f0, 0.0f0, 0.0f0,)),
    cLit = SVector{2,Float32}((0.0f0, 0.0f0,)),
    cSoil = SVector{2,Float32}((0.0f0, 0.0f0,)),
    cVegRoot = SVector{1,Float32}((0.0f0,)),
    cVegWood = SVector{1,Float32}((0.0f0,)),
    cVegLeaf = SVector{1,Float32}((0.0f0,)),
    cVegReserve = SVector{1,Float32}((0.0f0,)),
    cLitFast = SVector{1,Float32}((0.0f0,)),
    cLitSlow = SVector{1,Float32}((0.0f0,)),
    cSoilSlow = SVector{1,Float32}((0.0f0,)),
    cSoilOld = SVector{1,Float32}((0.0f0,)),
    cEco = SVector{8,Float32}((0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0,)),
    soilW = SVector{4,Float32}((0.0f0, 0.0f0, 0.0f0, 0.0f0,)),
    groundW = SVector{1,Float32}((0.0f0,)),
    snowW = SVector{1,Float32}((0.0f0,)),
    surfaceW = SVector{1,Float32}((0.0f0,)),
    TWS = SVector{7,Float32}((0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0,))
),
    ones = (;
    cVeg = SVector{4,Float32}((1.0f0, 1.0f0, 1.0f0, 1.0f0,)),
    cLit = SVector{2,Float32}((1.0f0, 1.0f0,)),
    cSoil = SVector{2,Float32}((1.0f0, 1.0f0,)),
    cVegRoot = SVector{1,Float32}((1.0f0,)),
    cVegWood = SVector{1,Float32}((1.0f0,)),
    cVegLeaf = SVector{1,Float32}((1.0f0,)),
    cVegReserve = SVector{1,Float32}((1.0f0,)),
    cLitFast = SVector{1,Float32}((1.0f0,)),
    cLitSlow = SVector{1,Float32}((1.0f0,)),
    cSoilSlow = SVector{1,Float32}((1.0f0,)),
    cSoilOld = SVector{1,Float32}((1.0f0,)),
    cEco = SVector{8,Float32}((1.0f0, 1.0f0, 1.0f0, 1.0f0, 1.0f0, 1.0f0, 1.0f0, 1.0f0,)),
    soilW = SVector{4,Float32}((1.0f0, 1.0f0, 1.0f0, 1.0f0,)),
    groundW = SVector{1,Float32}((1.0f0,)),
    snowW = SVector{1,Float32}((1.0f0,)),
    surfaceW = SVector{1,Float32}((1.0f0,)),
    TWS = SVector{7,Float32}((1.0f0, 1.0f0, 1.0f0, 1.0f0, 1.0f0, 1.0f0, 1.0f0,))
),
    vals = (;
    zix = (;
    cEco = Val{(cVeg = (1, 2, 3, 4), cLit = (5, 6), cSoil = (7, 8), cVegRoot = (1,), cVegWood = (2,), cVegLeaf = (3,), cVegReserve = (4,), cLitFast = (5,), cLitSlow = (6,), cSoilSlow = (7,), cSoilOld = (8,), cEco = (1, 2, 3, 4, 5, 6, 7, 8))}(),
    TWS = Val{(soilW = (1, 2, 3, 4), groundW = (5,), snowW = (6,), surfaceW = (7,), TWS = (1, 2, 3, 4, 5, 6, 7))}()
),
    self = (;
    cEco = Val{:cEco}(),
    TWS = Val{:TWS}()
),
    all_components = (;
    cEco = Val{(:cVeg, :cLit, :cSoil, :cVegRoot, :cVegWood, :cVegLeaf, :cVegReserve, :cLitFast, :cLitSlow, :cSoilSlow, :cSoilOld)}(),
    TWS = Val{(:soilW, :groundW, :snowW, :surfaceW)}()
)
),
    n_layers = (;
    cVeg = 4.0f0,
    cLit = 2.0f0,
    cSoil = 2.0f0,
    cVegRoot = 1.0f0,
    cVegWood = 1.0f0,
    cVegLeaf = 1.0f0,
    cVegReserve = 1.0f0,
    cLitFast = 1.0f0,
    cLitSlow = 1.0f0,
    cSoilSlow = 1.0f0,
    cSoilOld = 1.0f0,
    cEco = 8.0f0,
    soilW = 4.0f0,
    groundW = 1.0f0,
    snowW = 1.0f0,
    surfaceW = 1.0f0,
    TWS = 7.0f0
)
)
)
