import SindbadTEM.Processes as SM

# `Base.FieldError` (a structured exception for "type X has no field Y", thrown by
# `@unpack_nt`/property access on a NamedTuple) only exists from Julia 1.12 -- this package
# supports 1.10-1.12 (see SindbadTEM/Project.toml's `[compat] julia`). Pre-1.12, the same failure
# is a plain `ErrorException` with the same message text, so that's the fallback detection.
const _HAS_FIELD_ERROR = isdefined(Base, :FieldError)
function isMissingFieldError(e)
    e isa StagedError && return isMissingFieldError(e.original)
    _HAS_FIELD_ERROR && return e isa Base.FieldError
    return e isa ErrorException && occursin("has no field", e.msg)
end

# Tags which stage (`:define`/`:precompute`) of a chained define->precompute->compute check
# actually threw, so a bug in an approach's own `define` doesn't show up as an indistinguishable
# second "bug" under the `compute` phase (see checkComputeChain and outcomeFromException) --
# without this, testing `compute` (which necessarily re-runs this same approach's own
# define/precompute first, see the module comment above) makes one root-cause bug look like two.
struct StagedError <: Exception
    stage::Symbol
    original::Any
end

# `leafSubtypes` is already defined globally by scanApproachVariables.jl, included via
# testDataCoverage.jl before this file runs (see runtests.jl) -- reused as-is rather than
# redefined here, which used to silently overwrite that definition (harmless since both were
# identical, but fragile, and Julia warns about it).

# Recursively walk the returned `land` (nested NamedTuples of scalars/Arrays/SVectors) and
# report every NaN/Inf leaf by its full field path.
function findInvalidNumbers(x, path=Symbol[])
    invalid = Vector{Vector{Symbol}}()
    _collectInvalid!(invalid, x, path)
    return invalid
end
_collectInvalid!(invalid, x::AbstractFloat, path) = (isfinite(x) || push!(invalid, path); nothing)
function _collectInvalid!(invalid, x::Union{NamedTuple,Tuple}, path)
    foreach(pairs(x)) do (k, v)
        _collectInvalid!(invalid, v, k isa Symbol ? [path; k] : path)
    end
end
_collectInvalid!(invalid, x::AbstractArray, path) = foreach(v -> _collectInvalid!(invalid, v, path), x)
_collectInvalid!(invalid, x, path) = nothing

# Real SINDBAD runs (runTEMOne -> definePrecomputeTEM, then computeTEM; see
# SindbadTEM/src/Methods.jl) call every process's `define`+`precompute` in sequence first
# (threading `land` through all of them), and only *then*, in a completely separate pass, call
# `compute` for every process in the same order. A single static `land` input -- what this file
# used before -- is not what any approach actually sees: it's the land some *other* upstream
# choice of approaches would have produced. Instead: replay the real sequence with a reference
# approach per process (`reference_approaches`, generated by
# tools/benchmark/TestSindbadTEM/derive_sindbadTEM_test_data.jl straight from a real experiment's
# own `info.models.forward` -- an actual, internally-consistent model structure, not an arbitrary
# per-process fallback), and at each process slot *also* test every one of that process's
# approaches against the same, correctly-built-up upstream `land`. A process `reference_approaches`
# doesn't cover simply doesn't advance `land` for that step (see `advanceReference`) -- consistent
# with `LandEcosystem`'s own no-op default `define`/`precompute`/`compute`/`update` methods
# (SindbadTEM/src/Processes.jl) for a process no concrete approach was selected for, rather than
# inventing an arbitrary substitute.
#
# Each tested approach's own define -> precompute -> compute is chained together (output of one
# feeds the next, as `checkComputeChain` below does, called from the compute phase) rather than
# testing its `compute` against whatever the *reference* approach's `define`/`precompute` produced
# for this same process slot -- an approach that caches something in its own process's `land`
# namespace during `define`/`precompute` and reads it back in `compute` (a normal pattern) would
# otherwise fail a check that has nothing to do with a real bug, just because the reference
# approach for that process happens not to populate the same fields. The tested approach's own
# output still doesn't feed the *shared* chain, though -- only the reference approach's output
# advances what the *next* process sees in each phase, so testing one approach can't contaminate
# another's.
#
# A plain top-level assignment (not `const`), so re-`include`-ing this file (e.g. once per
# interactive session via SindbadTEM's Test package extension, rather than once per subprocess)
# doesn't trigger Julia's redefinition warnings the way re-including a `const` would.
_selected_by_process = let selected = Dict{Symbol,Any}()
    for name in reference_approaches
        T = getfield(SM, name)
        selected[nameof(supertype(T))] = T
    end
    selected
end
process_sequence = map(SM.standard_sindbad_model) do p
    (; process=p, process_type=getfield(SM, p), ref_type=get(_selected_by_process, p, nothing))
end
allowed_to_fail_set = Set(allowed_to_fail_approaches)

# model_number_type as the pools themselves.
test_num_type = eltype(land.pools.cEco)
# Matches tools/benchmark/TestSindbadTEM/experiment.json's temporal_resolution (the
# fixture's source) and getTypedModel's own default. Not derived dynamically: the
# fixture's tmp_helpers.dates is empty, same intentional stripping as num_type above.
test_model_timestep = "day"
typedApproach(::Type{T}) where {T <: LandEcosystem} = getTypedModel(nameof(T), test_model_timestep, test_num_type)

# `@inferred`'s own failure message prints the *entire* return type on both sides -- for a
# process's `land`, that's every field of every process's namespace, often thousands of
# characters, with the one field that actually diverges buried somewhere in the middle (see
# cCycleDisturbance_cFlow/cCycleDisturbance_WROASTED for real examples). This walks the concrete
# result type and the inferred type together, field by field (NamedTuple) / element by element
# (Tuple), and returns only the first path where they actually diverge -- `nothing` if they don't.
function firstUnstablePath(concrete::Type, inferred::Type, path::Vector{Any}=Any[])
    isconcretetype(inferred) || return (path, concrete, inferred)
    if concrete <: NamedTuple && inferred <: NamedTuple
        cnames, inames = fieldnames(concrete), fieldnames(inferred)
        cnames == inames || return (path, concrete, inferred)
        cfields, ifields = fieldtypes(concrete), fieldtypes(inferred)
        for i in eachindex(cnames)
            hit = firstUnstablePath(cfields[i], ifields[i], [path; cnames[i]])
            hit === nothing || return hit
        end
        return nothing
    elseif concrete <: Tuple && inferred <: Tuple
        cparams, iparams = concrete.parameters, inferred.parameters
        length(cparams) == length(iparams) || return (path, concrete, inferred)
        for i in eachindex(cparams)
            hit = firstUnstablePath(cparams[i], iparams[i], [path; i])
            hit === nothing || return hit
        end
        return nothing
    end
    return concrete === inferred ? nothing : (path, concrete, inferred)
end

# One-line description of a type instability, pinpointing the single diverging field/index (see
# `firstUnstablePath`) instead of dumping the full, deeply nested type on both sides.
function describeInstability(label, concrete::Type, inferred::Type)
    hit = firstUnstablePath(concrete, inferred)
    path, c, i = hit === nothing ? (Any[], concrete, inferred) : hit
    if isempty(path) && !isconcretetype(i) && c <: NamedTuple
        # Inference gave up completely at the top level -- e.g. an `if` whose branches only
        # sometimes reassign a variable (`land = f(...)` inside the `if`, untouched in the
        # implicit `else`) produces two differently-typed values for it, so there's no field-level
        # structure left on the inferred side to localize into. Naming the top-level fields is
        # still far shorter than the full (often huge, deeply nested) concrete type.
        return "$label is not type-stable: inference gave up completely (inferred type is plain `$(i)`, not concrete) -- often caused by a variable only conditionally reassigned across a branch (e.g. `if ...; land = f(...); end` with no `else`); top-level fields of the actual result: $(join(fieldnames(c), ", "))"
    end
    loc = isempty(path) ? "the return value itself" : join(path, ".")
    return "$label is not type-stable at `$loc`: concrete type at runtime is $(c), but inference only produced $(i)"
end

# Runs `f` and separately checks whether its return type is fully inferred for these argument
# types -- like `@inferred`, but always returns the actual (concrete, regardless of how well it
# inferred) result rather than throwing, and records a short diagnosis (see `describeInstability`)
# into `warn_ref` instead of failing. Used only for `define`: it runs once per model, not on the
# hot per-timestep path, so a type instability confined to `define` costs nothing at runtime and
# is a warning, never a hard failure -- unlike precompute/compute/update below, which do run every
# timestep and use `checkInferredHard` instead. Note this only checks `f`'s *own* inference: since
# Julia values always have a concrete runtime type, the concrete `land` this returns still lets
# precompute/compute infer cleanly against it even when `define` itself didn't.
function runAndCheckInferred(label, warn_ref, f, args...)
    result = f(args...)
    inferred = only(Base.return_types(f, typeof.(args)))
    (isconcretetype(inferred) && typeof(result) === inferred) && return result
    warn_ref[] = describeInstability(label, typeof(result), inferred)
    return result
end

# Hard-failing counterpart of `runAndCheckInferred`, for the hot-path functions (precompute,
# compute, update) where a type instability is a real bug, not just compiler noise -- same
# `@inferred`-equivalent check, but `error`s with the short `describeInstability` message instead
# of `@inferred`'s full-type dump.
function checkInferredHard(label, f, args...)
    result = f(args...)
    inferred = only(Base.return_types(f, typeof.(args)))
    (isconcretetype(inferred) && typeof(result) === inferred) || error(describeInstability(label, typeof(result), inferred))
    return result
end

# Function barriers: the inference checks above need to check against the concrete approach type,
# not the erased `Any`/abstract type a dynamic loop variable would have.
function checkDefinePrecompute(::Type{T}, forcing, land, helpers, warn_ref) where {T <: LandEcosystem}
    params = typedApproach(T)
    land = runAndCheckInferred("define", warn_ref, SM.define, params, forcing, land, helpers)
    return checkInferredHard("precompute", SM.precompute, params, forcing, land, helpers)
end
# `land` here is the upstream state *before* this process (built via the reference chain) --
# define/precompute/compute are chained for T itself, so compute sees exactly what T's own
# precompute would hand it in a real run, not some other approach's.
function checkComputeChain(::Type{T}, forcing, land, helpers, warn_ref) where {T <: LandEcosystem}
    params = typedApproach(T)
    land = try
        runAndCheckInferred("define", warn_ref, SM.define, params, forcing, land, helpers)
    catch e
        throw(StagedError(:define, e))
    end
    land = try
        checkInferredHard("precompute", SM.precompute, params, forcing, land, helpers)
    catch e
        throw(StagedError(:precompute, e))
    end
    return checkInferredHard("compute", SM.compute, params, forcing, land, helpers)
end
function checkUpdate(::Type{T}, forcing, land, helpers, warn_ref) where {T <: LandEcosystem}
    return checkInferredHard("update", SM.update, typedApproach(T), forcing, land, helpers)
end

# Zero-allocation checks: warm-up call (JIT-compiles, discarded), then a second, identical-input
# call whose allocations are measured. `define` is excluded -- it legitimately allocates (it's
# creating pools/arrays) -- but a well-written `precompute`/`compute` should allocate ~0 once
# compiled, so the tolerance here is exactly 0 bytes. Only checked in scoped runs (test-model,
# or a local `approaches` run) and only once the correctness check for the same approach has
# already passed (see the call sites below) -- no point measuring allocations on an approach
# that doesn't even run correctly.
function checkPrecomputeAllocation(T, forcing, land, helpers)
    try
        params = typedApproach(T)
        land_defined = SM.define(params, forcing, land, helpers)
        SM.precompute(params, forcing, land_defined, helpers)  # warm-up
        # The result must be captured (not discarded) inside the @allocated expression -- an
        # unused, side-effect-free call's allocation can otherwise be eliminated entirely by the
        # compiler, under-reporting real allocations. See benchmarkApproaches.jl's measureCall
        # for the same pattern.
        local result
        bytes = @allocated (result = SM.precompute(params, forcing, land_defined, helpers))
        bytes == 0 && return nothing
        return (; severity=:bug, reason="precompute allocated $bytes bytes on a hot call (expected 0)")
    catch e
        return outcomeFromException(e, "precompute allocation check")
    end
end
function checkComputeAllocation(T, forcing, land, helpers)
    try
        params = typedApproach(T)
        land_dp = SM.define(params, forcing, land, helpers)
        land_dp = SM.precompute(params, forcing, land_dp, helpers)
        SM.compute(params, forcing, land_dp, helpers)  # warm-up
        local result
        bytes = @allocated (result = SM.compute(params, forcing, land_dp, helpers))
        bytes == 0 && return nothing
        return (; severity=:bug, reason="compute allocated $bytes bytes on a hot call (expected 0)")
    catch e
        return outcomeFromException(e, "compute allocation check")
    end
end

# A missing-field error (thrown by `@unpack_nt`/property access when a NamedTuple genuinely
# doesn't have the requested field -- see `isMissingFieldError`) means the *data* this test
# combination provides is missing something the approach reads -- typically because the process
# being tested legitimately depends on a *different* process's approach (e.g. a specific
# soilWBase variant) than the one `reference_approaches` selects for that other process, or
# because that other process isn't covered by `reference_approaches` at all yet. That's a
# combination/coverage issue, not a bug in the approach under test, so it's tagged `:incompatible`
# and never hard-fails, even scoped (see `reportOutcome`). Anything else (UndefVarError -- e.g. a
# variable the approach's own code forgot to unpack; MethodError; type instability; ...) reflects
# the approach's own code and stays `:bug`-severity (hard-fails when scoped).
function outcomeFromException(e, label)
    if e isa StagedError
        base = outcomeFromException(e.original, label)
        return (; severity=base.severity, reason="[same root cause as this approach's own \"$(e.stage)\" row above] " * base.reason)
    end
    if isMissingFieldError(e)
        return (; severity=:incompatible, reason="$label found incompatible/missing upstream data (a different or not-yet-covered approach for an upstream process, not a bug in this approach): " * sprint(showerror, e))
    end
    return (; severity=:bug, reason="$label errored: " * sprint(showerror, e))
end

# Per-approach `:bug`-severity results are informational, not a hard gate, UNLESS running scoped
# (`approaches` passed to runApproachTests) -- see runApproachTests's docstring. `:incompatible`
# results are always informational, scoped or not -- see `outcomeFromException`. Many "failures"
# across the full, unscoped catalog are inherent, mutually exclusive structural requirements
# between approaches of the same process (e.g. soilWBase_smax1Layer hard-requires exactly 1 soil
# layer while soilWBase_smax2Layer requires 2 -- the shared reference land/helpers can only match
# one of them at a time), not bugs.
# Returns `nothing` on success, or `(; severity, reason)` otherwise. `warn_ref` is how
# `checkDefinePrecompute`/`checkComputeChain` report a type instability confined to `define`
# (see `runAndCheckInferred`) without throwing -- it doesn't fail the check, but still needs to
# surface as `:define_unstable` (never `:bug`) rather than silently vanishing into a plain pass.
function approachOutcome(check_fn, T, forcing, land, helpers)
    warn_ref = Ref{Union{Nothing,String}}(nothing)
    try
        result = check_fn(T, forcing, land, helpers, warn_ref)
        result isa NamedTuple || return (; severity=:bug, reason="did not return a NamedTuple")
        invalid_paths = findInvalidNumbers(result)
        if !isempty(invalid_paths)
            return (; severity=:bug, reason="NaN/Inf at " * join((join(p, ".") for p in invalid_paths), ", "))
        end
        warn_ref[] === nothing && return nothing
        return (; severity=:define_unstable, reason=warn_ref[])
    catch e
        return outcomeFromException(e, "check")
    end
end

# The reference approach for a process comes from a real experiment's own model structure (see
# the module-level comment above), so it should always succeed -- but a process
# `reference_approaches` doesn't cover has `ref_type === nothing`, and if the reference approach
# nonetheless errors against this test's specific forcing/helpers, `land` is left unchanged for
# that step (a warning is logged) rather than aborting the whole sequential chain -- downstream
# processes just won't see that one process's contribution, same as a true no-op.
function advanceReference(f, ref_type, forcing, land, helpers, step_label)
    ref_type === nothing && return land
    try
        return f(typedApproach(ref_type), forcing, land, helpers)
    catch e
        @warn "Reference approach failed while advancing the sequential chain; leaving `land` unchanged for this step" step = step_label ref = ref_type exception = e
        return land
    end
end

# An approach in `allowed_to_fail_approaches` (SindbadTEM/test/test_data/referenceApproaches.jl,
# hand-maintained -- a documented, already-triaged pre-existing issue) still gets tested/checked
# exactly like any other approach; this only kicks in once it's *already* failed, downgrading the
# outcome's severity to `:warn` (regardless of whether it would otherwise have been `:bug` or
# `:incompatible`) so it's still visibly reported but never added to `scoped_problems` -- so it
# can never hard-fail a scoped test_model() run. A genuine pass stays a pass; this only lowers the
# bar for a failure that's already known about, it doesn't grant a free pass.
function applyAllowedToFail(outcome, T)
    outcome === nothing && return nothing
    # `:define_unstable` is already unconditionally non-blocking (see `runAndCheckInferred`) with
    # its own accurate message -- don't relabel it as an allow-listed `:warn`, which would claim
    # it's a pre-triaged issue from `allowed_to_fail_approaches` when it isn't.
    outcome.severity == :define_unstable && return outcome
    nameof(T) in allowed_to_fail_set || return outcome
    return (; severity=:warn, reason=outcome.reason)
end

# `outcomes` maps approach name -> `(; severity, reason)` (see `outcomeFromException`).
# `:incompatible` results (missing upstream data from this test's reference selection for some
# *other* process, not a bug) are always informational. `:define_unstable` results (see
# `runAndCheckInferred`) are always informational too -- a type instability confined to `define`
# doesn't cost anything at runtime (`define` runs once per model, not the hot per-timestep path).
# `:warn` results (see `applyAllowedToFail`) are always informational too, same as
# `:incompatible`. `:bug` results are informational too UNLESS `scoped`, in which case they're
# also added to `scoped_problems` to hard-fail the run.
function reportOutcome(phase_label, outcomes, n_total, scoped, scoped_problems)
    n_ok = n_total - length(outcomes)
    if isempty(outcomes)
        @info "$phase_label: all $n_total approaches OK"
        return
    end
    incompatible = Dict(k => v.reason for (k, v) in outcomes if v.severity == :incompatible)
    define_unstable = Dict(k => v.reason for (k, v) in outcomes if v.severity == :define_unstable)
    warnings = Dict(k => v.reason for (k, v) in outcomes if v.severity == :warn)
    bugs = Dict(k => v.reason for (k, v) in outcomes if v.severity == :bug)
    if !isempty(incompatible)
        @info "$phase_label: $(length(incompatible))/$n_total approaches skipped -- missing or mutually-exclusive upstream data, not a bug (see SindbadTEM/test/README.md)" incompatible
    end
    if !isempty(define_unstable)
        @info "$phase_label: $(length(define_unstable))/$n_total approaches have a type instability confined to `define` -- define runs once per model (not the hot per-timestep path), so this is never a hard failure, even scoped" define_unstable
    end
    if !isempty(warnings)
        @warn "$phase_label: $(length(warnings))/$n_total approaches failed but are in allowed_to_fail_approaches -- known, pre-triaged issues (see SindbadTEM/test/test_data/referenceApproaches.jl), never a hard failure" warnings
    end
    if !isempty(bugs)
        @warn "$phase_label: $(length(bugs))/$n_total approaches failed/errored -- informational only, not a hard failure unless scoped (see SindbadTEM/test/README.md)" n_ok bugs
        if scoped
            for (name, reason) in bugs
                scoped_problems["$phase_label: $name"] = reason
            end
        end
    end
end

function runDefinePrecomputePhase(land0, tested_functions, wanted, scoped, scoped_problems)
    land = land0
    test_dp = :define in tested_functions || :precompute in tested_functions
    outcomes = Dict{String,Any}()
    n_total = 0
    for step in process_sequence
        land_before = land
        if test_dp
            for T in leafSubtypes(step.process_type)
                wanted(T) || continue
                n_total += 1
                outcome = approachOutcome(checkDefinePrecompute, T, tmp_forcing, deepcopy(land_before), tmp_helpers)
                if outcome === nothing && scoped
                    outcome = checkPrecomputeAllocation(T, tmp_forcing, deepcopy(land_before), tmp_helpers)
                end
                outcome = applyAllowedToFail(outcome, T)
                outcome === nothing || (outcomes[string(nameof(T))] = outcome)
            end
        end
        # advance the chain using the reference approach for this process only -- always,
        # regardless of whether this phase's approaches are under test, since the compute phase
        # needs a properly-built-up `land` either way.
        land = advanceReference(SM.define, step.ref_type, tmp_forcing, land, tmp_helpers, (step.process, :define))
        land = advanceReference(SM.precompute, step.ref_type, tmp_forcing, land, tmp_helpers, (step.process, :precompute))
    end
    test_dp && reportOutcome("define+precompute (sequential)", outcomes, n_total, scoped, scoped_problems)
    return land
end

function runComputePhase(land0, tested_functions, wanted, scoped, scoped_problems)
    land = land0
    test_compute = :compute in tested_functions
    outcomes = Dict{String,Any}()
    n_total = 0
    for step in process_sequence
        land_before = land
        if test_compute
            for T in leafSubtypes(step.process_type)
                wanted(T) || continue
                n_total += 1
                # checkComputeChain re-runs T's own define+precompute on top of `land_before`
                # (which already has *earlier* processes' real compute output threaded in, from
                # this same loop) so T's compute sees exactly what T's own precompute would hand
                # it in a real run -- not the reference approach's define/precompute output for
                # this same process slot (see the module-level comment above).
                outcome = approachOutcome(checkComputeChain, T, tmp_forcing, deepcopy(land_before), tmp_helpers)
                if outcome === nothing && scoped
                    outcome = checkComputeAllocation(T, tmp_forcing, deepcopy(land_before), tmp_helpers)
                end
                outcome = applyAllowedToFail(outcome, T)
                outcome === nothing || (outcomes[string(nameof(T))] = outcome)
            end
        end
        land = advanceReference(SM.compute, step.ref_type, tmp_forcing, land, tmp_helpers, (step.process, :compute))
    end
    test_compute && reportOutcome("compute (sequential)", outcomes, n_total, scoped, scoped_problems)
    return land
end

"""
    runApproachTests(; functions=("define", "precompute", "compute"), approaches=nothing, processes=nothing)

Run every check in `SindbadTEM/test/checkApproaches.jl` -- see `SindbadTEM/test/README.md` for
what each one means -- and return `nothing`, or throw if running **scoped**
(`approaches !== nothing`) and something targeted failed.

- `functions`: which of `"define"`/`"precompute"`/`"compute"`/`"update"` to check. `update` is
  excluded by default -- it's a separate, optional per-timestep path (only invoked when
  `inline_update` is set in `experiment.json`) that most approaches don't override, so checking
  it by default mostly just measures how many approaches happen to inherit the no-op default
  against a land state most of them were never designed to see.
- `approaches`: `nothing` (the default) checks every approach, informationally (logs `@info`/
  `@warn`, never throws on a per-approach problem -- see `approachOutcome`'s docstring for why).
  Passing approach struct names (as `AbstractString`s or `Symbol`s) scopes the run to just those
  and makes it a hard gate: throws if any of them fails correctness (errors, isn't type-stable in
  `precompute`/`compute`/`update`, produces `NaN`/`Inf`) *or* allocates on a warm
  `precompute`/`compute` call -- **unless** that approach is listed in `allowed_to_fail_approaches`
  (`SindbadTEM/test/test_data/referenceApproaches.jl`, hand-maintained), in which case a failure is
  logged as `:warn` and never hard-fails, even scoped (see `applyAllowedToFail`). A type
  instability confined to `define` itself is a separate, always-non-blocking `:define_unstable`
  outcome (see `runAndCheckInferred`) -- `define` runs once per model, not the hot per-timestep
  path, and its own inference quality doesn't affect what `precompute`/`compute` see (Julia values
  always have a concrete runtime type, however well `define`'s *code* inferred).
- `processes`: `nothing` (the default) doesn't restrict by process. Passing process names (e.g.
  `"soilProperties"`, as `AbstractString`s or `Symbol`s) restricts the run to just those
  processes' own leaf approaches -- unlike `approaches`, this alone does **not** make the run
  scoped/hard-gated (that's still controlled by `approaches` only); combine both to hard-gate a
  whole process at once. Errors immediately if a name doesn't match any process in
  `standard_sindbad_model`, listing the valid names, rather than silently matching nothing.

This is what CI's `test-model` (scoped) and `analyse-tem` (unscoped) jobs both run, and what
`SindbadTEM`'s exported `test_model`/`analyse_tem`/`analyse_process` (see
`SindbadTEM/src/DevTools.jl` and `SindbadTEM/ext/SindbadTEMTestExt.jl`) call directly, in-process.
"""
function runApproachTests(; functions=("define", "precompute", "compute"), approaches=nothing, processes=nothing)
    tested_functions = Set(Symbol.(functions))
    tested_approaches = approaches === nothing ? nothing : Set(Symbol.(approaches))
    scoped = tested_approaches !== nothing
    tested_processes = if processes === nothing
        nothing
    else
        wanted_processes = Set(Symbol.(processes))
        known_processes = Set(step.process for step in process_sequence)
        unknown = setdiff(wanted_processes, known_processes)
        isempty(unknown) || error(
            "unknown process name(s): $(join(sort(string.(unknown)), ", ")) -- valid names are: " *
            join(sort(string.(collect(known_processes))), ", "),
        )
        wanted_processes
    end
    wanted(T) = (tested_approaches === nothing || nameof(T) in tested_approaches) &&
                (tested_processes === nothing || nameof(supertype(T)) in tested_processes)
    scoped_problems = Dict{String,String}()

    # Pure type-hierarchy check, no simulation involved: every process in standard_sindbad_model
    # is an abstract LandEcosystem subtype, and every one of its leaf approaches is a concrete
    # subtype of that specific process (not just of LandEcosystem in general). Unlike the
    # per-approach define/precompute/compute/update checks below, this one is a real, reliable
    # `@test` gate -- it's pure reflection, always either holds or signals an actual structural
    # bug -- so it always runs, scoped or not.
    @testset "Process/approach type hierarchy" verbose = true begin
        for step in process_sequence
            tested_processes === nothing || step.process in tested_processes || continue
            @test step.process_type <: LandEcosystem
            @testset "$(step.process)" begin
                for T in leafSubtypes(step.process_type)
                    wanted(T) || continue
                    @test T <: step.process_type
                    @test !isabstracttype(T)
                end
            end
        end
    end

    # `purpose(T)` (SindbadTEM/src/Types.jl) has a generic fallback,
    # `purpose(T::Type{<:LandEcosystem})`, for any subtype that doesn't define its own -- for a
    # concrete leaf approach (no subtypes of its own), that fallback's
    # `foreach(subtypes(T)) do ... end` never runs its body and returns `nothing` instead of a
    # description, rather than throwing. So checking that `purpose(T)` actually is a real,
    # non-empty string is how to reliably catch an approach missing its own
    # `purpose(::Type{$T}) = "..."` definition. Pure reflection, no simulation involved -- like the
    # type-hierarchy check above, this always runs, scoped or not.
    @testset "Approach purpose defined" verbose = true begin
        for step in process_sequence
            tested_processes === nothing || step.process in tested_processes || continue
            @testset "$(step.process)" begin
                for T in leafSubtypes(step.process_type)
                    wanted(T) || continue
                    p = try
                        SM.purpose(T)
                    catch
                        nothing
                    end
                    @test p isa AbstractString && !isempty(p)
                end
            end
        end
    end

    land_after_definePrecompute = runDefinePrecomputePhase(deepcopy(land), tested_functions, wanted, scoped, scoped_problems)
    land_after_compute = runComputePhase(deepcopy(land_after_definePrecompute), tested_functions, wanted, scoped, scoped_problems)

    # `update` is a separate, optional per-timestep path (only invoked when `inline_update` is
    # set in experiment.json), not part of the base define/precompute/compute pipeline above --
    # tested independently per approach against the fully-built final land state, not chained.
    if :update in tested_functions
        outcomes = Dict{String,Any}()
        approaches_to_test = filter(wanted, leafSubtypes(LandEcosystem))
        for T in approaches_to_test
            outcome = approachOutcome(checkUpdate, T, tmp_forcing, deepcopy(land_after_compute), tmp_helpers)
            outcome = applyAllowedToFail(outcome, T)
            outcome === nothing || (outcomes[string(nameof(T))] = outcome)
        end
        reportOutcome("update", outcomes, length(approaches_to_test), scoped, scoped_problems)
    end

    # Scoped runs hard-fail here if anything targeted failed/errored. Unscoped runs (analyse-tem,
    # or `approaches=nothing`) never reach this: `scoped` is false, so scoped_problems is never
    # populated in the first place.
    if scoped && !isempty(scoped_problems)
        details = join(("$k -- $v" for (k, v) in scoped_problems), "\n  ")
        error("$(length(scoped_problems)) check(s) failed for the tested approach(es):\n  $details")
    end
    return nothing
end

# Script-mode entry point: when included directly (by runtests.jl -> runApproachChecks.jl, i.e.
# every CI job), run once using the same SINDBADTEM_TEST_FUNCTIONS/SINDBADTEM_TEST_APPROACHES
# environment variables as before, so CI/subprocess behavior is unchanged from a plain
# `julia --project=SindbadTEM SindbadTEM/test/runApproachChecks.jl` run. Skipped when this file
# is included just to pick up the function/`process_sequence` definitions for interactive,
# in-process use (SindbadTEM/ext/SindbadTEMTestExt.jl sets SINDBADTEM_SKIP_AUTORUN=true before
# including it, then calls runApproachTests directly, possibly many times with different
# arguments in one session).
if get(ENV, "SINDBADTEM_SKIP_AUTORUN", "false") != "true"
    default_functions = split(get(ENV, "SINDBADTEM_TEST_FUNCTIONS", "define,precompute,compute"), ",")
    approaches_raw = strip(get(ENV, "SINDBADTEM_TEST_APPROACHES", ""))
    default_approaches = isempty(approaches_raw) ? nothing : split(approaches_raw, ",")
    runApproachTests(; functions=default_functions, approaches=default_approaches)
end
