import SindbadTEM.Processes as SM

# Which of define/precompute/compute/update to actually test, customizable via
# SINDBADTEM_TEST_FUNCTIONS (comma-separated, e.g. "define,precompute,compute,update").
# `update` is excluded by default: it's a separate, optional per-timestep path (only invoked
# when `inline_update` is set in experiment.json) that most approaches don't override, so
# testing it by default mostly just measures how many approaches happen to inherit the no-op
# default against a land state most of them were never designed to see.
const DEFAULT_TESTED_FUNCTIONS = "define,precompute,compute"
const TESTED_FUNCTIONS = Set(Symbol.(split(get(ENV, "SINDBADTEM_TEST_FUNCTIONS", DEFAULT_TESTED_FUNCTIONS), ",")))

# Which approaches to actually test, customizable via SINDBADTEM_TEST_APPROACHES (comma-separated
# approach struct names, e.g. "soilProperties_Saxton1986,soilWBase_smax1Layer"). Unset/empty
# (the default) means no filter -- test every approach, same as always. Used by the
# test-model CI job to scope a run down to just the approaches whose own file changed in a given
# push, instead of the full catalog test-tem/analyse-tem always run -- see
# .github/workflows/SindbadTEM-benchmark.yml.
const TESTED_APPROACHES_RAW = strip(get(ENV, "SINDBADTEM_TEST_APPROACHES", ""))
const TESTED_APPROACHES = isempty(TESTED_APPROACHES_RAW) ? nothing : Set(Symbol.(split(TESTED_APPROACHES_RAW, ",")))
wantedApproach(T) = TESTED_APPROACHES === nothing || nameof(T) in TESTED_APPROACHES

# `leafSubtypes` is already defined globally by scanApproachVariables.jl, included via
# testDataCoverage.jl before this file runs (see runtests.jl) -- reused as-is rather than
# redefined here, which used to silently overwrite that definition (harmless since both were
# identical, but fragile, and Julia warns about it).

# Recursively walk the returned `land` (nested NamedTuples of scalars/Arrays/SVectors) and
# report every NaN/Inf leaf by its full field path.
function findInvalidNumbers(x, path=Symbol[])
    invalid = Vector{Vector{Symbol}}()
    _collectInvalid!(invalid, x, path)
    return invalid
end
_collectInvalid!(invalid, x::AbstractFloat, path) = (isfinite(x) || push!(invalid, path); nothing)
function _collectInvalid!(invalid, x::Union{NamedTuple,Tuple}, path)
    foreach(pairs(x)) do (k, v)
        _collectInvalid!(invalid, v, k isa Symbol ? [path; k] : path)
    end
end
_collectInvalid!(invalid, x::AbstractArray, path) = foreach(v -> _collectInvalid!(invalid, v, path), x)
_collectInvalid!(invalid, x, path) = nothing

# Real SINDBAD runs (runTEMOne -> definePrecomputeTEM, then computeTEM; see
# SindbadTEM/src/Methods.jl) call every process's `define`+`precompute` in sequence first
# (threading `land` through all of them), and only *then*, in a completely separate pass, call
# `compute` for every process in the same order. A single static `land` input -- what this
# file used before -- is not what any approach actually sees: it's the land some *other* upstream
# choice of approaches would have produced. Instead: replay the real sequence with a reference
# approach (`reference_approaches`, generated by tools/benchmark/TestSindbadTEM/derive_sindbadTEM_test_data.jl
# from a real run of tools/benchmark/TestSindbadTEM/, falling back to an arbitrary default for the
# few processes it doesn't select) at every process slot, and at each slot ALSO test every one of that process's
# approaches against the same, correctly-built-up upstream `land` -- without letting the tested
# approach's own output feed forward (only the reference approach's output advances the chain).
reference_sequence = map(SM.standard_sindbad_model) do p
    process_type = getfield(SM, p)
    ref_type = getfield(SM, getproperty(reference_approaches, p))
    (; process=p, process_type, ref_type)
end

# Function barriers: `@inferred` needs to check against the concrete approach type, not the
# erased `Any`/abstract type a dynamic loop variable would have.
function checkDefinePrecompute(::Type{T}, forcing, land, helpers) where {T <: LandEcosystem}
    params = T()
    land = @inferred SM.define(params, forcing, land, helpers)
    return @inferred SM.precompute(params, forcing, land, helpers)
end
function checkCompute(::Type{T}, forcing, land, helpers) where {T <: LandEcosystem}
    return @inferred SM.compute(T(), forcing, land, helpers)
end
function checkUpdate(::Type{T}, forcing, land, helpers) where {T <: LandEcosystem}
    return @inferred SM.update(T(), forcing, land, helpers)
end

# Per-approach results are informational, not a `Pkg.test` gate: many "failures" here are
# inherent, mutually exclusive structural requirements between approaches of the same process
# (e.g. soilWBase_smax1Layer hard-requires exactly 1 soil layer while soilWBase_smax2Layer
# requires 2 -- the shared reference land/helpers can only match one of them at a time), not
# bugs, so hard-failing `Pkg.test` on them would make the required CI check permanently red.
# Returns `nothing` on success, or a short problem description otherwise.
function approachOutcome(check_fn, T, forcing, land, helpers)
    try
        result = check_fn(T, forcing, land, helpers)
        result isa NamedTuple || return "did not return a NamedTuple"
        invalid_paths = findInvalidNumbers(result)
        isempty(invalid_paths) && return nothing
        return "NaN/Inf at " * join((join(p, ".") for p in invalid_paths), ", ")
    catch e
        return "errored: " * sprint(showerror, e)
    end
end

# Each phase is wrapped in a function (rather than reassigning `land` in a top-level `for` loop)
# to avoid Julia's top-level "soft scope" ambiguity, where an assignment to an existing global
# from inside a `for` loop silently creates a new loop-local shadow instead of updating it.

# The reference approach picked for a process is usually TestSindbadTEM's own model_structure.json
# selection (known-good), but for the handful of processes it doesn't select at all, it's an arbitrary fallback (see
# derive_sindbadTEM_test_data.jl) that isn't guaranteed to actually succeed against this
# test data. If it fails, leave `land` unchanged rather than aborting the whole sequential chain
# -- downstream processes just won't see that one process's contribution, same as if it were a
# true no-op.
function advanceReference(f, ref, forcing, land, helpers, step_label)
    try
        return f(ref, forcing, land, helpers)
    catch e
        @warn "Reference approach failed while advancing the sequential chain; leaving `land` unchanged for this step" step = step_label ref = typeof(ref) exception = e
        return land
    end
end

function reportOutcome(phase_label, problems, n_total)
    n_ok = n_total - length(problems)
    if isempty(problems)
        @info "$phase_label: all $n_total approaches OK"
    else
        @warn "$phase_label: $(length(problems))/$n_total approaches failed/errored -- informational only, not a Pkg.test failure (see SindbadTEM/test/README.md)" n_ok problems
    end
end

function runDefinePrecomputePhase(land0)
    land = land0
    test_this_phase = :define in TESTED_FUNCTIONS || :precompute in TESTED_FUNCTIONS
    problems = Dict{String,String}()
    n_total = 0
    for step in reference_sequence
        if test_this_phase
            for T in leafSubtypes(step.process_type)
                wantedApproach(T) || continue
                n_total += 1
                reason = approachOutcome(checkDefinePrecompute, T, tmp_forcing, deepcopy(land), tmp_helpers)
                reason === nothing || (problems[string(nameof(T))] = reason)
            end
        end
        # advance the chain using the reference approach for this process only -- always,
        # regardless of whether this phase's approaches are under test, since `compute`
        # needs a properly-built-up `land` either way.
        ref = step.ref_type()
        land = advanceReference(SM.define, ref, tmp_forcing, land, tmp_helpers, (step.process, :define))
        land = advanceReference(SM.precompute, ref, tmp_forcing, land, tmp_helpers, (step.process, :precompute))
    end
    test_this_phase && reportOutcome("define+precompute (sequential)", problems, n_total)
    return land
end

function runComputePhase(land0)
    land = land0
    test_this_phase = :compute in TESTED_FUNCTIONS
    problems = Dict{String,String}()
    n_total = 0
    for step in reference_sequence
        if test_this_phase
            for T in leafSubtypes(step.process_type)
                wantedApproach(T) || continue
                n_total += 1
                reason = approachOutcome(checkCompute, T, tmp_forcing, deepcopy(land), tmp_helpers)
                reason === nothing || (problems[string(nameof(T))] = reason)
            end
        end
        land = advanceReference(SM.compute, step.ref_type(), tmp_forcing, land, tmp_helpers, (step.process, :compute))
    end
    test_this_phase && reportOutcome("compute (sequential)", problems, n_total)
    return land
end

# Pure type-hierarchy check, no simulation involved: every process in standard_sindbad_model is
# an abstract LandEcosystem subtype, and every one of its leaf approaches is a concrete subtype
# of that specific process (not just of LandEcosystem in general). Unlike the per-approach
# define/precompute/compute/update checks above, this one is a real, reliable `@test` gate --
# it's pure reflection, always either holds or signals an actual structural bug.
@testset "Process/approach type hierarchy" verbose = true begin
    for step in reference_sequence
        @test step.process_type <: LandEcosystem
        @testset "$(step.process)" begin
            for T in leafSubtypes(step.process_type)
                @test T <: step.process_type
                @test !isabstracttype(T)
            end
        end
    end
end

land_after_definePrecompute = runDefinePrecomputePhase(deepcopy(land))
land_after_compute = runComputePhase(deepcopy(land_after_definePrecompute))

# `update` is a separate, optional per-timestep path (only invoked when `inline_update` is set in
# experiment.json), not part of the base define/precompute/compute pipeline above -- tested
# independently per approach against the fully-built final land state, not chained. Excluded by
# default (see TESTED_FUNCTIONS at the top of this file).
if :update in TESTED_FUNCTIONS
    problems = Dict{String,String}()
    approaches = filter(wantedApproach, leafSubtypes(LandEcosystem))
    for T in approaches
        reason = approachOutcome(checkUpdate, T, tmp_forcing, deepcopy(land_after_compute), tmp_helpers)
        reason === nothing || (problems[string(nameof(T))] = reason)
    end
    reportOutcome("update", problems, length(approaches))
end
