import SindbadTEM.Processes as SM

# `leafSubtypes` is already defined globally by scanApproachVariables.jl, included via
# testDataCoverage.jl before this file runs (see runtests.jl) -- reused as-is rather than
# redefined here, which used to silently overwrite that definition (harmless since both were
# identical, but fragile, and Julia warns about it).

# Recursively walk the returned `land` (nested NamedTuples of scalars/Arrays/SVectors) and
# report every NaN/Inf leaf by its full field path.
function findInvalidNumbers(x, path=Symbol[])
    invalid = Vector{Vector{Symbol}}()
    _collectInvalid!(invalid, x, path)
    return invalid
end
_collectInvalid!(invalid, x::AbstractFloat, path) = (isfinite(x) || push!(invalid, path); nothing)
function _collectInvalid!(invalid, x::Union{NamedTuple,Tuple}, path)
    foreach(pairs(x)) do (k, v)
        _collectInvalid!(invalid, v, k isa Symbol ? [path; k] : path)
    end
end
_collectInvalid!(invalid, x::AbstractArray, path) = foreach(v -> _collectInvalid!(invalid, v, path), x)
_collectInvalid!(invalid, x, path) = nothing

# Real SINDBAD runs (runTEMOne -> definePrecomputeTEM, then computeTEM; see
# SindbadTEM/src/Methods.jl) call every process's `define`+`precompute` in sequence first
# (threading `land` through all of them), and only *then*, in a completely separate pass, call
# `compute` for every process in the same order. A single static `land` input -- what this
# file used before -- is not what any approach actually sees: it's the land some *other* upstream
# choice of approaches would have produced. Instead: replay the real sequence with a reference
# approach (`reference_approaches`, generated by tools/benchmark/TestSindbadTEM/derive_sindbadTEM_test_data.jl
# from a real run of tools/benchmark/TestSindbadTEM/, falling back to an arbitrary default for the
# few processes it doesn't select) at every process slot, and at each slot ALSO test every one of that process's
# approaches against the same, correctly-built-up upstream `land` -- without letting the tested
# approach's own output feed forward (only the reference approach's output advances the chain).
#
# A plain top-level assignment (not `const`), so re-`include`-ing this file (e.g. once per
# interactive session via tools/dev_test.jl, rather than once per subprocess) doesn't trigger
# Julia's redefinition warnings the way re-including a `const` would.
reference_sequence = map(SM.standard_sindbad_model) do p
    process_type = getfield(SM, p)
    ref_type = getfield(SM, getproperty(reference_approaches, p))
    (; process=p, process_type, ref_type)
end

# Function barriers: `@inferred` needs to check against the concrete approach type, not the
# erased `Any`/abstract type a dynamic loop variable would have.
function checkDefinePrecompute(::Type{T}, forcing, land, helpers) where {T <: LandEcosystem}
    params = T()
    land = @inferred SM.define(params, forcing, land, helpers)
    return @inferred SM.precompute(params, forcing, land, helpers)
end
function checkCompute(::Type{T}, forcing, land, helpers) where {T <: LandEcosystem}
    return @inferred SM.compute(T(), forcing, land, helpers)
end
function checkUpdate(::Type{T}, forcing, land, helpers) where {T <: LandEcosystem}
    return @inferred SM.update(T(), forcing, land, helpers)
end

# Zero-allocation checks: warm-up call (JIT-compiles, discarded), then a second, identical-input
# call whose allocations are measured. `define` is excluded -- it legitimately allocates (it's
# creating pools/arrays) -- but a well-written `precompute`/`compute` should allocate ~0 once
# compiled, so the tolerance here is exactly 0 bytes. Only checked in scoped runs (test-model,
# or a local `approaches` run) and only once the correctness check for the same approach has
# already passed (see the call sites below) -- no point measuring allocations on an approach
# that doesn't even run correctly.
function checkPrecomputeAllocation(T, forcing, land, helpers)
    try
        params = T()
        land_defined = SM.define(params, forcing, land, helpers)
        SM.precompute(params, forcing, land_defined, helpers)  # warm-up
        # The result must be captured (not discarded) inside the @allocated expression -- an
        # unused, side-effect-free call's allocation can otherwise be eliminated entirely by the
        # compiler, under-reporting real allocations. See benchmarkApproaches.jl's measureCall
        # for the same pattern.
        local result
        bytes = @allocated (result = SM.precompute(params, forcing, land_defined, helpers))
        bytes == 0 && return nothing
        return "precompute allocated $bytes bytes on a hot call (expected 0)"
    catch e
        return "precompute allocation check errored: " * sprint(showerror, e)
    end
end
function checkComputeAllocation(T, forcing, land, helpers)
    try
        params = T()
        SM.compute(params, forcing, land, helpers)  # warm-up
        local result
        bytes = @allocated (result = SM.compute(params, forcing, land, helpers))
        bytes == 0 && return nothing
        return "compute allocated $bytes bytes on a hot call (expected 0)"
    catch e
        return "compute allocation check errored: " * sprint(showerror, e)
    end
end

# Per-approach results are informational, not a hard gate, UNLESS running scoped (`approaches`
# passed to runApproachTests) -- see runApproachTests's docstring. Many "failures" across the
# full, unscoped catalog are inherent, mutually exclusive structural requirements between
# approaches of the same process (e.g. soilWBase_smax1Layer hard-requires exactly 1 soil layer
# while soilWBase_smax2Layer requires 2 -- the shared reference land/helpers can only match one
# of them at a time), not bugs.
# Returns `nothing` on success, or a short problem description otherwise.
function approachOutcome(check_fn, T, forcing, land, helpers)
    try
        result = check_fn(T, forcing, land, helpers)
        result isa NamedTuple || return "did not return a NamedTuple"
        invalid_paths = findInvalidNumbers(result)
        isempty(invalid_paths) && return nothing
        return "NaN/Inf at " * join((join(p, ".") for p in invalid_paths), ", ")
    catch e
        return "errored: " * sprint(showerror, e)
    end
end

# The reference approach picked for a process is usually TestSindbadTEM's own model_structure.json
# selection (known-good), but for the handful of processes it doesn't select at all, it's an arbitrary fallback (see
# derive_sindbadTEM_test_data.jl) that isn't guaranteed to actually succeed against this
# test data. If it fails, leave `land` unchanged rather than aborting the whole sequential chain
# -- downstream processes just won't see that one process's contribution, same as if it were a
# true no-op.
function advanceReference(f, ref, forcing, land, helpers, step_label)
    try
        return f(ref, forcing, land, helpers)
    catch e
        @warn "Reference approach failed while advancing the sequential chain; leaving `land` unchanged for this step" step = step_label ref = typeof(ref) exception = e
        return land
    end
end

function reportOutcome(phase_label, problems, n_total, scoped, scoped_problems)
    n_ok = n_total - length(problems)
    if isempty(problems)
        @info "$phase_label: all $n_total approaches OK"
    else
        @warn "$phase_label: $(length(problems))/$n_total approaches failed/errored -- informational only, not a hard failure unless scoped (see SindbadTEM/test/README.md)" n_ok problems
        if scoped
            for (name, reason) in problems
                scoped_problems["$phase_label: $name"] = reason
            end
        end
    end
end

function runDefinePrecomputePhase(land0, tested_functions, wanted, scoped, scoped_problems)
    land = land0
    test_this_phase = :define in tested_functions || :precompute in tested_functions
    problems = Dict{String,String}()
    n_total = 0
    for step in reference_sequence
        if test_this_phase
            for T in leafSubtypes(step.process_type)
                wanted(T) || continue
                n_total += 1
                reason = approachOutcome(checkDefinePrecompute, T, tmp_forcing, deepcopy(land), tmp_helpers)
                if reason === nothing && scoped
                    reason = checkPrecomputeAllocation(T, tmp_forcing, deepcopy(land), tmp_helpers)
                end
                reason === nothing || (problems[string(nameof(T))] = reason)
            end
        end
        # advance the chain using the reference approach for this process only -- always,
        # regardless of whether this phase's approaches are under test, since `compute`
        # needs a properly-built-up `land` either way.
        ref = step.ref_type()
        land = advanceReference(SM.define, ref, tmp_forcing, land, tmp_helpers, (step.process, :define))
        land = advanceReference(SM.precompute, ref, tmp_forcing, land, tmp_helpers, (step.process, :precompute))
    end
    test_this_phase && reportOutcome("define+precompute (sequential)", problems, n_total, scoped, scoped_problems)
    return land
end

function runComputePhase(land0, tested_functions, wanted, scoped, scoped_problems)
    land = land0
    test_this_phase = :compute in tested_functions
    problems = Dict{String,String}()
    n_total = 0
    for step in reference_sequence
        if test_this_phase
            for T in leafSubtypes(step.process_type)
                wanted(T) || continue
                n_total += 1
                reason = approachOutcome(checkCompute, T, tmp_forcing, deepcopy(land), tmp_helpers)
                if reason === nothing && scoped
                    reason = checkComputeAllocation(T, tmp_forcing, deepcopy(land), tmp_helpers)
                end
                reason === nothing || (problems[string(nameof(T))] = reason)
            end
        end
        land = advanceReference(SM.compute, step.ref_type(), tmp_forcing, land, tmp_helpers, (step.process, :compute))
    end
    test_this_phase && reportOutcome("compute (sequential)", problems, n_total, scoped, scoped_problems)
    return land
end

"""
    runApproachTests(; functions=("define", "precompute", "compute"), approaches=nothing)

Run every check in `SindbadTEM/test/testApproaches.jl` -- see `SindbadTEM/test/README.md` for
what each one means -- and return `nothing`, or throw if running **scoped**
(`approaches !== nothing`) and something targeted failed.

- `functions`: which of `"define"`/`"precompute"`/`"compute"`/`"update"` to check. `update` is
  excluded by default -- it's a separate, optional per-timestep path (only invoked when
  `inline_update` is set in `experiment.json`) that most approaches don't override, so checking
  it by default mostly just measures how many approaches happen to inherit the no-op default
  against a land state most of them were never designed to see.
- `approaches`: `nothing` (the default) checks every approach, informationally (logs `@info`/
  `@warn`, never throws on a per-approach problem -- see `approachOutcome`'s docstring for why).
  Passing approach struct names (as `AbstractString`s or `Symbol`s) scopes the run to just those
  and makes it a hard gate: throws if any of them fails correctness (errors, isn't type-stable,
  produces `NaN`/`Inf`) *or* allocates on a warm `precompute`/`compute` call.

This is what CI's `test-model` (scoped) and `analyse-tem` (unscoped) jobs both run, and what
`tools/dev_test.jl`'s `test_model`/`analyse_tem` call directly, in-process.
"""
function runApproachTests(; functions=("define", "precompute", "compute"), approaches=nothing)
    tested_functions = Set(Symbol.(functions))
    tested_approaches = approaches === nothing ? nothing : Set(Symbol.(approaches))
    scoped = tested_approaches !== nothing
    wanted(T) = tested_approaches === nothing || nameof(T) in tested_approaches
    scoped_problems = Dict{String,String}()

    # Pure type-hierarchy check, no simulation involved: every process in standard_sindbad_model
    # is an abstract LandEcosystem subtype, and every one of its leaf approaches is a concrete
    # subtype of that specific process (not just of LandEcosystem in general). Unlike the
    # per-approach define/precompute/compute/update checks below, this one is a real, reliable
    # `@test` gate -- it's pure reflection, always either holds or signals an actual structural
    # bug -- so it always runs, scoped or not.
    @testset "Process/approach type hierarchy" verbose = true begin
        for step in reference_sequence
            @test step.process_type <: LandEcosystem
            @testset "$(step.process)" begin
                for T in leafSubtypes(step.process_type)
                    @test T <: step.process_type
                    @test !isabstracttype(T)
                end
            end
        end
    end

    land_after_definePrecompute = runDefinePrecomputePhase(deepcopy(land), tested_functions, wanted, scoped, scoped_problems)
    land_after_compute = runComputePhase(deepcopy(land_after_definePrecompute), tested_functions, wanted, scoped, scoped_problems)

    # `update` is a separate, optional per-timestep path (only invoked when `inline_update` is
    # set in experiment.json), not part of the base define/precompute/compute pipeline above --
    # tested independently per approach against the fully-built final land state, not chained.
    if :update in tested_functions
        problems = Dict{String,String}()
        approaches_to_test = filter(wanted, leafSubtypes(LandEcosystem))
        for T in approaches_to_test
            reason = approachOutcome(checkUpdate, T, tmp_forcing, deepcopy(land_after_compute), tmp_helpers)
            reason === nothing || (problems[string(nameof(T))] = reason)
        end
        reportOutcome("update", problems, length(approaches_to_test), scoped, scoped_problems)
    end

    # Scoped runs hard-fail here if anything targeted failed/errored. Unscoped runs (analyse-tem,
    # or `approaches=nothing`) never reach this: `scoped` is false, so scoped_problems is never
    # populated in the first place.
    if scoped && !isempty(scoped_problems)
        details = join(("$k -- $v" for (k, v) in scoped_problems), "\n  ")
        error("$(length(scoped_problems)) check(s) failed for the tested approach(es):\n  $details")
    end
    return nothing
end

# Script-mode entry point: when included directly (by runtests.jl -> runApproachChecks.jl, i.e.
# every CI job), run once using the same SINDBADTEM_TEST_FUNCTIONS/SINDBADTEM_TEST_APPROACHES
# environment variables as before, so CI/subprocess behavior is unchanged from a plain
# `julia --project=SindbadTEM SindbadTEM/test/runApproachChecks.jl` run. Skipped when this file
# is included just to pick up the function/`reference_sequence` definitions for interactive,
# in-process use (tools/dev_test.jl sets SINDBADTEM_SKIP_AUTORUN=true before including it, then
# calls runApproachTests directly, possibly many times with different arguments in one session).
if get(ENV, "SINDBADTEM_SKIP_AUTORUN", "false") != "true"
    default_functions = split(get(ENV, "SINDBADTEM_TEST_FUNCTIONS", "define,precompute,compute"), ",")
    approaches_raw = strip(get(ENV, "SINDBADTEM_TEST_APPROACHES", ""))
    default_approaches = isempty(approaches_raw) ? nothing : split(approaches_raw, ",")
    runApproachTests(; functions=default_functions, approaches=default_approaches)
end
